spring:
    datasource:

#        url: jdbc:mysql://13.239.238.92:3306/ott_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        url: jdbc:mysql://13.239.238.92:3306/ott_db

        username: root
        password: Nungil12!@
        driver-class-name: com.mysql.cj.jdbc.Driver

    data:
      mongodb:
          uri: mongodb://admin:Nungil12!%40@13.239.238.92:27017/kmdb
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
aws:
    s3:
        bucket-name: nungil.file.server
        access-key: AKIAQXUIX56G4ZEWYU56
        secret-key: ${AWS_S3_SECRET_KEY:default_key_if_missing}
        region: ap-northeast-2
server:
    port: 8080
    ssl:
        enabled: false
    servlet:
        context-path: /

#    mybatis:
#        config-location: classpath:mybatis/mybatis-config.xml
#        mapper-locations: classpath:mybatis/mapper/**/*.xml
mybatis:
    mapper-locations:
        - classpath:mapper/**/*.xml  # MyBatis 매퍼 파일 위치를 설정합니다. **는 모든 디렉토리, *.xml은 모든 XML 파일을 의미합니다.
    configuration:
        map-underscore-to-camel-case: true  # 데이터베이스의 언더스코어 네이밍(예: column_name)을 자바의 카멜케이스 네이밍(예: columnName)으로 매핑합니다.
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # SQL 로깅 구현체를 설정합니다. 이 설정을 통해 콘솔에 SQL 로그를 출력합니다.

logging:
    level:
        org.apache.ibatis: DEBUG  # MyBatis 로깅 레벨을 DEBUG로 설정하여, 실행되는 SQL 쿼리와 내부 로깅 정보를 콘솔에 출력합니다.
        org.springframework.web: DEBUG  # Spring Web 요청 처리 로그
        com.nungil.repository: DEBUG
        org.springframework.jdbc.core: DEBUG

api:
    kobis:
        api-key: b6294028408df8733f4113de4cc9f206
    kmdb:
        serviceKey: 18JYN87W3523502WR6Y3

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        mappings:
            enabled: true
