spring:
    datasource:
        url: jdbc:mysql://13.239.238.92:3306/ott_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        username: root
        password: Nungil12!@
        driver-class-name: com.mysql.cj.jdbc.Driver

    data:
      mongodb:
          uri: mongodb://admin:Nungil12!%40@13.239.238.92:27017/ott_crawler

    mybatis:
        config-location: classpath:mybatis/mybatis-config.xml
        mapper-locations: classpath:mybatis/mapper/**/*.xml
