spring:
    datasource:

#        url: jdbc:mysql://13.239.238.92:3306/ott_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        url: jdbc:mysql://13.239.238.92:3306/ott_db?characterEncoding=UTF-8

        username: root
        password: Nungil12!@
        driver-class-name: com.mysql.cj.jdbc.Driver

    data:
      mongodb:
          uri: mongodb://admin:Nungil12!%40@13.239.238.92:27017/kmdb
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
r2:
    endpoint: https://417727e547627d7b68d4af33b70de7c1.r2.cloudflarestorage.com
    bucketName: nungil
    accessKey: a48aaf0d193b5c910b4c9e3e45d28219
    secretKey: 92860996217d439307a57fcf1ca68e8c44255622744cb6956cb3d6525b833542
    publicUrl: https://pub-929f1ad902524142bbef9d16447060e3.r2.dev
server:
    address: 0.0.0.0
    port: 8080
    ssl:
        enabled: false
    servlet:
        context-path: /

#    mybatis:
#        config-location: classpath:mybatis/mybatis-config.xml
#        mapper-locations: classpath:mybatis/mapper/**/*.xml
mybatis:
    mapper-locations:
        - classpath:mapper/**/*.xml  # MyBatis 매퍼 파일 위치를 설정합니다. **는 모든 디렉토리, *.xml은 모든 XML 파일을 의미합니다.
    configuration:
        map-underscore-to-camel-case: true  # 데이터베이스의 언더스코어 네이밍(예: column_name)을 자바의 카멜케이스 네이밍(예: columnName)으로 매핑합니다.
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # SQL 로깅 구현체를 설정합니다. 이 설정을 통해 콘솔에 SQL 로그를 출력합니다.

logging:
    level:
        org.apache.ibatis: DEBUG  # MyBatis 로깅 레벨을 DEBUG로 설정하여, 실행되는 SQL 쿼리와 내부 로깅 정보를 콘솔에 출력합니다.
        org.springframework.web: DEBUG  # Spring Web 요청 처리 로그
        com.nungil.repository: DEBUG
        org.springframework.jdbc.core: DEBUG

api:
    kobis:
        api-key: b6294028408df8733f4113de4cc9f206
    kmdb:
        serviceKey: 18JYN87W3523502WR6Y3
    tmdb:
        key: 0d40786ff6fad61ec32b2acf510cdfdf

file:
    upload-dir: /home/ec2-user/uploads

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        mappings:
            enabled: true
