name: Java CI with Gradle
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin

      - name: Set execute permission for gradlew
        run: |
          chmod +x gradlew
          ls -lah gradlew  # 변경 사항 확인

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info  # 직접 실행

      - name: Get JAR_FILE
        id: jarfile
        run: |
          JAR_FILE=$(ls build/libs/*.jar | grep -v plain | head -n 1)
          if [ -z "$JAR_FILE" ]; then
            echo "❌ JAR 파일이 생성되지 않았습니다."
            exit 1
          fi
          echo "JAR_FILE=${JAR_FILE}" >> $GITHUB_ENV
          echo "✅ 생성된 JAR 파일: ${JAR_FILE}"
