name: Java CI with Gradle
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin

      - name: Set execute permission for gradlew
        run: |
          chmod +x gradlew
          ls -lah gradlew  # 변경 사항 확인

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info  # 직접 실행

      - name: Get JAR_FILE
        id: jarfile
        run: |
          JAR_FILE=$(ls build/libs/*.jar | grep -v plain | head -n 1)
          if [ -z "$JAR_FILE" ]; then
            echo "❌ JAR 파일이 생성되지 않았습니다."
            exit 1
          fi
          echo "JAR_FILE=${JAR_FILE}" >> $GITHUB_ENV
          echo "✅ 생성된 JAR 파일: ${JAR_FILE}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.AWS_EC2_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Restart Spring Application on EC2
        run: |
          JAR_FILE=$(basename $(ls build/libs/*.jar | head -n 1))
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << EOF
            pgrep java | xargs kill -9;
            nohup java -jar /home/${{ secrets.AWS_EC2_USER }}/$JAR_FILE > app.log 2>&1 &
          EOF
